### ISSUE TITLE
Can't test changes made to the fork

### ISSUE THREAD

**Issue by g-yui** [acidicoala/dream-api#3]
When building with the given script, even with no changes to the source, it will return a "Failed to execute main script" error.
Aside from that, testing main.py returns a FileNotFound error, as  dev_working_dir\DreamAPI.log does not exist.

It's possible I'm doing something wrong, if so please let me now!

The log file created by the executable is just this:
`[%A totally reasonable time to be awake forking%][DEBUG]	Setting log level to DEBUG`

**Comment by acidicoala** [comment]
I have made some improvements to code portability and added instructions to run the project from source: https://github.com/acidicoala/dream-api#running-from-source
Could you test it to see if the instructions work for you?

**Comment by g-yui** [comment]
Same issue, here's the traceback:
`Traceback (most recent call last):
  File "C:\Users\%MyUserName%\Desktop\dream-api-1.1.1\src\main.py", line 5, in <module>
    from gui.app_window import ApplicationWindow
  File "C:\Users\%MyUserName%\Desktop\dream-api-1.1.1\src\gui\app_window.py", line 5, in <module>
    from setup.config import config_path, config
  File "C:\Users\%MyUserName%\Desktop\dream-api-1.1.1\src\setup\config.py", line 6, in <module>
    from util.log import log
  File "C:\Users\%MtUserName%\Desktop\dream-api-1.1.1\src\util\log.py", line 31, in <module>
    log = Log()
  File "C:\Users\%MyUserName%\Desktop\dream-api-1.1.1\src\util\singleton.py", line 6, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\%MyUserName%\Desktop\dream-api-1.1.1\src\util\log.py", line 17, in __new__
    fileHandler = FileHandler(log_path, 'w')
  File "C:\Users\%MyUserName%\.pyenv\pyenv-win\versions\3.9.0a4-win32\lib\logging\__init__.py", line 1144, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\%MyUserName%\.pyenv\pyenv-win\versions\3.9.0a4-win32\lib\logging\__init__.py", line 1173, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\%MyUserName%\\Desktop\\dev_working_dir\\DreamAPI.log'
`

Odd thing that of the double \\ , even so, the file does not exist either way, is that file perhaps a trace from another one made during testing?

**Comment by acidicoala** [comment]
Are you running the `python src\main.py` from the project's root directory?

**Comment by g-yui** [comment]
Indeed

**Comment by acidicoala** [comment]
I've added the `dev_working_dir` in one of the latest commits, so no wonder you did not get it before. Also, I would advise against using global python interpreters and instead creating per-project virtual environment, so that dependencies from different project don't conflict with each other.

**Comment by g-yui** [comment]
gotcha!
